server:
  port: 8989
  hostname: 你的IP
logging:
  config: null
first: false
initSearch: false
myEmail: 邮箱
gpt:
  token: openai token
  model: text-davinci-002-render-sha-mobile
meilisearch:
  apiHost: http://${server.hostname}:7700
  apiKey: apikey
upload:
  max:
    size:
      image: 5
      file: 300
  uri: https://${server.hostname}/${upload.prefix}
  path: /zsy/myBlog/app/static
  prefix: static/
spring:
  mail:
    password: password
    username: username
    default-encoding: UTF-8
    host: smtp.163.com
  application:
    name: ZSY-ADMIN
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: zsy
    url: jdbc:postgresql://${server.hostname}:5432/shuyu_blog?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Shanghai
    driver-class-name: org.postgresql.Driver
    password: password
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  data:
    redis:
      host: ${server.hostname}
      port: 6379
      password: password
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
          max-wait: -1
  jackson:
    date-format: yyyy年MM月dd日 HH:mm
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
